### ISSUE TITLE
Since Rancher 2.8.3 with Machine image "v0.15.0-rancher110" + latest centos rhel stream 9 Cluster nodes are looping on creating/deleting server

### ISSUE THREAD

**Issue by med-jordan** [nutanix/docker-machine#101]
### Nutanix Cluster Information
AOS 6.5.5.5
pc.2022.6.0.9

### Rancher Version
2.8.3

### Rancher Node Driver Version
3.6

### Expected Behavior
Successfull Node deployment without errors.

### Actual Behavior
Since Rancher 2.8.3 with Machine image version "v0.15.0-rancher110" Cluster nodes are looping on creating/deleting server on new and existing clusters using centos Rhel stream 9 latest image.
"command: sudo hostname testcl01-pool1-a9f476fd-slm2c && echo "testcl01-pool1-a9f476fd-slm2c" | sudo tee /etc/hostname err: inappropriate ioctl for device output: )"

### Important Factors
​

**Comment by tuxtof** [comment]
Hello @med-jordan 

I found the problem and it is unrelated to nutanix, in all case ssh connection is not managed by the rancher node driver but by the rancher-machine binary

In the rancher/machine:v0.15.0-rancher110 container they remove the ssh binary from the image (on purpose or not) so now the rancher-machine binary use a SSH Go native implementation as we can see in the log

```
SSH binary not found, using native Go implementation
```

And this is the reason why it broke against recent OS like centos-9-stream

**Comment by tuxtof** [comment]
fix by https://github.com/rancher/machine/pull/240
