### ISSUE TITLE
 ssh command error: command: exit 0 err: exit status 255 output- Not a network problem

### ISSUE THREAD

**Issue by eyanez111** [nutanix/docker-machine#20]
After we solved the Driver connection with the update on ticket https://github.com/nutanix/docker-machine/issues/18#issuecomment-1005425027 I was able to create clusters on the DEV env, now I am trying to do it on a different cluster (UAT and PROD) but I am getting this errors:

2022/01/05 22:07:08 [INFO] [node-controller-rancher-machine] Using SSH client ty                                                                             pe: external
2022/01/05 22:07:08 [INFO] [node-controller-rancher-machine] Using SSH private k                                                                             ey: /management-state/node/nodes/cp1/machines/cp1/id_rsa (-rw-------)
2022/01/05 22:07:08 [INFO] [node-controller-rancher-machine] &{[-F /dev/null -o                                                                              ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=non                                                                             e -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o St                                                                             rictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@172.22.140.176 -o Id                                                                             entitiesOnly=yes -i /management-state/node/nodes/cp1/machines/cp1/id_rsa -p 22]                                                                              /usr/bin/ssh <nil>}
2022/01/05 22:07:08 [INFO] [node-controller-rancher-machine] About to run SSH co                                                                             mmand:
2022/01/05 22:07:08 [INFO] [node-controller-rancher-machine] exit 0
2022/01/05 22:07:08 [INFO] [node-controller-rancher-machine] SSH cmd err, output                                                                             : exit status 255:
2022/01/05 22:07:08 [INFO] [node-controller-rancher-machine] Error getting ssh c                                                                             ommand 'exit 0' : ssh command error: command: exit 0 err: exit status 255 output                                                                             :
2022/01/05 22:07:10 [INFO] [node-controller-rancher-machine] SSH cmd err, output                                                                             : exit status 255:
2022/01/05 22:07:10 [INFO] [node-controller-rancher-machine] Error getting ssh c                                                                             ommand 'exit 0' : ssh command error: command: exit 0 err: exit status 255 output                                                                             :
2022/01/05 22:07:11 [INFO] [node-controller-rancher-machine] Getting to WaitForS                                                                             SH function...
2022/01/05 22:07:11 [INFO] [node-controller-rancher-machine] (cp1) Calling .GetS                                                                             SHHostname
2022/01/05 22:07:11 [INFO] [node-controller-rancher-machine] (cp1) Calling .GetS                                                                             SHPort
2022/01/05 22:07:11 [INFO] [node-controller-rancher-machine] (cp1) Calling .GetS                                                                             SHKeyPath
 
here is the whole file:
[logs.txt](https://github.com/nutanix/docker-machine/files/7818065/logs.txt)

I checked with the networking team and they have opened all the ports and allow the IP from the Rancher server to this Nutanix cluster. Also it does build and deletes VM's. There is just this SSH error that I am not sure why I keep getting and it does not allow the cluster build to be completed. After testing it works perfect on the dev cluster I want to now start playing around in AUT to possible in a future take it to prod. One thing to add is that on Dev we are using CentOs and on UAT we are using Ubuntu. Not sure if it is an OS thing.

Thanks
Francisco Yanez
DevOps Manager from ZE Power Group (NUTANIX partner)

**Comment by tuxtof** [comment]
Hello @eyanez111 there is a problem with the ubuntu image you are using

i see in the log that your image is "ubuntu-20.04.3-live-server-amd64.iso" 

this is not what is expected, you need to use a template cloud image
the iso is a livecd/installer

for exemple in your case use the following template and all will be OK

https://cloud-images.ubuntu.com/focal/20220105/focal-server-cloudimg-amd64-disk-kvm.img

take care

**Comment by eyanez111** [comment]
For some reason I am getting an error about installing DOCKER
<img width="949" alt="Screenshot 2022-01-06 161328" src="https://user-images.githubusercontent.com/685470/148470773-38cd2f32-3ab3-472b-9804-08e64720b89c.png">


I looked a few times at the installation and it fails right after the apt-get, while is doing the curl to get docker "curl -fsSl https://download.docker.com/linux/ubuntu/gpg". Is this something Ubuntu related? if that is the case I can go with Centos just like I did in Dev, I just do not want to deploy prod in centos due the stop of patches that is coming to Centos 7. If  Centos is the only Option what Image do you recommend

Here are the logs just in case:

[logs.txt](https://github.com/nutanix/docker-machine/files/7825467/logs.txt)


thanks for all the help we are really close. 

Francisco Yanez
DevOps Manager at ZE Power Group - Nutanix Partner

**Comment by tuxtof** [comment]
Hello @eyanez111 

there is a problem with your Rancher Node Template
in Engine Options you are using an old Docker Install URL who don't support recent distribution like your ubuntu
https://releases.rancher.com/install-docker/18.09.sh

you need to use the default recent one
https://releases.rancher.com/install-docker/20.10.sh
and it will fix your docker install problem

<img width="857" alt="image" src="https://user-images.githubusercontent.com/180613/148536688-6e5578f9-55ab-4b12-b1da-640c310d4bdf.png">

**Comment by eyanez111** [comment]
It worked!

thanks so much!!

**Comment by tuxtof** [comment]
👍🏻
