### ISSUE TITLE
Rancher Nutanix Node Template Issue

### ISSUE THREAD

**Issue by Gareddyc** [nutanix/docker-machine#21]
### Rancher Version
 Rancher: 2.6.4

### Rancher Node Driver Version : V3.1.0

https://github.com/nutanix/docker-machine/releases/download/v3.1.0/docker-machine-driver-nutanix_v3.1.0_linux

### Node template

Cluster Name: xyz
Endpoint: https:test.com
usre id: abc
Pass: *****
Port: 9440
VMImage: ntnx-1.2
VMNetwork: v1681_162.11.180.0-24

### Debug Output
Error: [cmdCreateInner] error setting machine configuration from flags provided: nutanix-vm-network cannot be empty:Timeout waiting for ssh key

### Expected Behavior
It should create a RKE1 Nutanix cluster sucessfully

### Actual Behavior
 
 We are trying to add Nutanix Node and Cluster Driver. After that we are try to create node template to get Nutanix driver args information from Nutanix. We could see the following parameters are not fetching from nutanix cluster.

nutanix-endpoint
nutanix-username
nutanix-password
nutanix-vm-network
nutanix-vm-image

### Important Factors
> The Below node driver information provide

Download URL: https://github.com/nutanix/docker-machine/releases/download/v3.1.0/docker-machine-driver-nutanix_v3.1.0_linux

#Custom UI URL: https://nutanix.github.io/rancher-ui-driver/v3.1.0/component.js (If we add this link we are seeing Error: "There was an error trying to load custom driver nutanix. Please verify the custom node driver settings.undefined")

Checksum: e8f4f2e7ae7e927534884b5a3a45a38a5bd2c2872de1d65375f6e009bed75dba

Whitelist Domains: nutanix.github.io
​
### References

https://github.com/nutanix/docker-machine

**Comment by tuxtof** [comment]
Hello @Gareddyc 

based on what you give in your ticket i already have multiple remark

endpoint: you need to give an hostname or an IP, no http prefix here
VMImage: i don't know exactly what is this ntnx-1.2 image (look like but not exactly as the Karbon one) , the image here need to be a template of cloud-image cloud-init ready with an OS supported by rancher

to try to dig can you give me the additional information:

output of `kubectl get nodetemplates.management.cattle.io -A  -o yaml` on the local cluster (be careful to remove your password) 

logs of the rancher pods on the local cluster during the creation of a new cluster with the nutanix node driver
please active debug mode before by following the documentation here 
https://rancher.com/docs/rancher/v2.6/en/troubleshooting/logging/

**Comment by Gareddyc** [comment]
Thanks for your reply!!!

**Endpoint:** nut.abc.com
**VMImage:** Rancher_template (ubuntu 18.0.4)

- We are unbale deploy RKE cluster due to Rancher Node Template Issue and VM Image not fetching from Nutanix custom Ubuntu 18.0.4 Image which we created. 

-`> kubectl -n cattle-system logs -l app=rancher -c rancher (Rancher Pod Logs)

W0428 22:07:36.590631 33 transport.go:288] Unable to cancel request for *client.addQuery
W0428 22:07:40.793576 33 transport.go:288] Unable to cancel request for *client.addQuery
W0428 22:07:42.241710 33 transport.go:288] Unable to cancel request for *client.addQuery
W0428 22:11:50.480891 33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0428 22:15:57.474424 33 transport.go:288] Unable to cancel request for *client.addQuery
W0428 22:17:30.004737 33 transport.go:288] Unable to cancel request for *client.addQuery
W0428 22:17:30.004821 33 transport.go:288] Unable to cancel request for *client.addQuery
W0428 22:17:30.729657 33 transport.go:288] Unable to cancel request for *client.addQuery
W0428 22:17:31.306968 33 transport.go:288] Unable to cancel request for *client.addQuery
W0428 22:20:33.482707 33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
2022/04/28 21:26:04 [ERROR] defaultSvcAccountHandler: Sync: error handling default ServiceAccount of namespace key=p-nwrwl, err=Operation cannot be fulfilled on namespaces "p-nwrwl": the object has been modified; please apply your changes to the latest version and try again
W0428 21:33:43.981663 34 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0428 21:41:48.982225 34 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0428 21:47:17.983017 34 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0428 21:54:25.984573 34 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0428 22:01:15.986092 34 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0428 22:06:34.989033 34 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
2022/04/28 22:11:03 [ERROR] Error during subscribe websocket: close sent
W0428 22:15:11.990360 34 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0428 22:22:42.991880 34 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
2022/04/28 22:22:39 [INFO] Generating and uploading node config controler2
2022/04/28 22:22:54 [ERROR] error syncing 'c-fn2lx/m-27n2l': handler node-controller: [cmdCreateInner] error setting machine configuration from flags provided: nutanix-vm-network cannot be empty, requeuing
2022/04/28 22:24:39 [INFO] Creating jail for c-fn2lx
2022/04/28 22:24:39 [INFO] Provisioning node worker2
2022/04/28 22:24:39 [INFO] Generating and uploading node config worker2
2022/04/28 22:24:54 [ERROR] error syncing 'c-fn2lx/m-kqq2d': handler node-controller: [cmdCreateInner] error setting machine configuration from flags provided: nutanix-vm-network cannot be empty, requeuing
2022/04/28 22:24:55 [INFO] Creating jail for c-fn2lx
2022/04/28 22:24:55 [INFO] Provisioning node controler1
2022/04/28 22:24:55 [INFO] Generating and uploading node config controler1
2022/04/28 22:25:10 [ERROR] error syncing 'c-fn2lx/m-6dgpg': handler node-controller: [cmdCreateInner] error setting machine configuration from flags provided: nutanix-vm-network cannot be empty, requeuing
>`

Please see the output of kubectl get nodetemplates.management.cattle.io -A -o yaml.

`apiVersion: v1
items:
- amazonec2Config: null
  apiVersion: management.cattle.io/v3
  kind: NodeTemplate
  metadata:
    annotations:
      field.cattle.io/creatorId: u-2tt5cq4nqz
      ownerBindingsCreated: "true"
    creationTimestamp: "2022-04-27T17:28:38Z"
    generateName: nt-
    generation: 9
    labels:
      cattle.io/creator: norman
    name: nt-dlrv5
    namespace: cattle-global-nt
    resourceVersion: "6782939"
    uid: cbccc765-e761-4532-86cc-b50154aa374e
  nutanixConfig:
    cloudInit: ""
    cluster: c2-j74-bna1
    diskSize: "0"
    endpoint: nut.abc.tsc
    insecure: true
    password: ''
    port: "9440"
    storageContainer: ""
    username: svc_rancher@abc.tsc
    vmCategories: []
    vmCores: "1"
    vmCpuPassthrough: false
    vmCpus: "2"
    vmImage: Rancher_template---SCSI.0-1
    vmImageSize: "0"
    vmMem: "2048"
    vmNetwork: null
  spec:
    cloudCredentialName: null
    displayName: NutanixRKENode
    driver: nutanix
    engineEnv: {}
    engineInstallURL: https://releases.rancher.com/install-docker/20.10.sh
    engineLabel: {}
    engineOpt: {}
    engineRegistryMirror: []
    engineStorageDriver: null
    useInternalIpAddress: true
- amazonec2Config: null
  apiVersion: management.cattle.io/v3
  kind: NodeTemplate
  metadata:
    annotations:
      field.cattle.io/creatorId: u-un7ieer4vh
      ownerBindingsCreated: "true"
    creationTimestamp: "2022-04-27T18:14:09Z"
    generateName: nt-
    generation: 1
    labels:
      cattle.io/creator: norman
    name: nt-szwkt
    namespace: cattle-global-nt
    resourceVersion: "6280456"
    uid: 20640ec9-5694-470a-b2b8-d3c58084b2d5
  nutanixConfig:
    cloudInit: ""
    cluster: c2-j74-bna1
    diskSize: "0"
    endpoint: nut.abc.tsc:9440/
    insecure: true
    password: 
    port: "9440"
    storageContainer: ""
    username: abc@supply.com
    vmCores: "1"
    vmCpuPassthrough: false
    vmCpus: "2"
    vmImage: ""
    vmImageSize: "0"
    vmMem: "2048"
    vmNetwork: null
  spec:
    cloudCredentialName: null
    displayName: Test
    driver: nutanix
    engineInstallURL: https://releases.rancher.com/install-docker/20.10.sh
    engineRegistryMirror: []
    useInternalIpAddress: true
- amazonec2Config: null
  apiVersion: management.cattle.io/v3
  kind: NodeTemplate
  metadata:
    annotations:
      field.cattle.io/creatorId: user-k59pq
      ownerBindingsCreated: "true"
    creationTimestamp: "2022-04-27T21:22:13Z"
    generateName: nt-
    generation: 5
    labels:
      cattle.io/creator: norman
    name: nt-wq2c6
    namespace: cattle-global-nt
    resourceVersion: "6802773"
    uid: 87ae2712-d11f-4cbd-b6fd-968bfe2e3fa0
  nutanixConfig:
    cloudInit: '#cloud-config'
    cluster: c2-j74-bna1
    diskSize: "0"
    endpoint: nut.abc.tsc
    insecure: true
    password: ''
    port: "9440"
    storageContainer: ""
    username: svc_rancher@abc.tbc
    vmCategories: []
    vmCores: "1"
    vmCpuPassthrough: false
    vmCpus: "2"
    vmImage: Rancher_template---SCSI.0-1
    vmImageSize: "50"
    vmMem: "4096"
    vmNetwork:
    - v1781_172.17.181.0-24
  spec:
    cloudCredentialName: null
    displayName: NutanixRKE1
    driver: nutanix
    engineEnv: {}
    engineInstallURL: https://releases.rancher.com/install-docker/20.10.sh
    engineLabel: {}
    engineOpt: {}
    engineRegistryMirror: []
    useInternalIpAddress: true
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
> `

**Comment by Gareddyc** [comment]
Hi @ tuxtof,

In the Node Template we can see the vlan/subnet information(Network). But somehow its not showing in yaml file.

> During RKE cluster creation we are selecting the correct Node template.  Still seeing same error: [cmdCreateInner] error setting machine configuration from flags provided: nutanix-vm-network cannot be empty:Timeout waiting for ssh key

**Comment by tuxtof** [comment]
on the nodetemplate output you give me we see 3 template , one have the network configured (NutanixRKE1) the two others no (Test, NutanixRKENode)

which one did you try to use it ?

**Comment by Gareddyc** [comment]
I am trying to use NutanixRKE1 Template.

![image](https://user-images.githubusercontent.com/22626683/165985183-9ba328f4-c540-4b1d-8d2a-aae6e740c496.png)
![image](https://user-images.githubusercontent.com/22626683/165985317-ec161b90-7ffb-4c90-acdd-b99b1573ccf0.png)

**Comment by tuxtof** [comment]
ok this node template seems ok

please can you active debug mode by following the documentation here
https://rancher.com/docs/rancher/v2.6/en/troubleshooting/logging/

and show me the rancher log during the deployment of a new cluster

**Comment by tuxtof** [comment]
@Gareddyc any news ?

**Comment by pipoe2h** [comment]
Hi,

I had the same issue, and after some troubleshooting, I discovered that my k3s was running on the same network as my target Nutanix cluster. By default, k3s networks are 10.42.0.0/16 (pod) and 10.43.0.0/16 (service). Make sure that your k3s is not using the same subnet as your Nutanix cluster because if it does, the requests of the Rancher server won't leave the k3s machine.

To change the network values for k3s during installation check https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#networking 

An example
```shell
curl -sfL https://get.k3s.io | sh -s - \
    --write-kubeconfig-mode 644 \
    --cluster-cidr 172.16.0.0/16 \
    --service-cidr 172.17.0.0/16 \
    --cluster-dns 172.17.0.10`

**Comment by tuxtof** [comment]
No update, please reopen if needed
