### ISSUE TITLE
Labels support

### ISSUE THREAD

**Issue by tuxtof** [nutanix/docker-machine#24]
**Is your feature request related to a problem? Please describe.**
Allow to add labels to VM

**Comment by rhunt-ntx** [comment]
Is this in relation to Kubernetes NodePool Labels by chance? The form item exists for this but it doesn't actually work. Node pools just fail to provision with a bogus error message. 

```
 message: 'Error creating machine: Error in driver during machine creation: error:
      {'
```

**Comment by rhunt-ntx** [comment]
understood

+1 for the prism central labels
