### ISSUE TITLE
CLuster Provisioning issue

### ISSUE THREAD

**Issue by pdaccache** [nutanix/docker-machine#50]
Dears,

Once i try to create a new cluster, i am receiving the below error:
Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference:Timeout waiting for ssh key

i have tried different versions of node driver and still same error please advise.

**Comment by pdaccache** [comment]
i have managed to make it work once i changed the template image

**Comment by tuxtof** [comment]
Usually best is to use official cloud-image from distributor (Ubuntu, RedHat, Rocky, Debian, ....)

the main prerequisite is cloud-init package

nice you fix it
