### ISSUE TITLE
Cluster created using rancher, will appear in nutanix karbon?

### ISSUE THREAD

**Issue by pdaccache** [nutanix/docker-machine#51]
Dears,

If i provision a cluster using rancher, does it appear in nutanix karbon as a cluster or we can see the VMs only in prism central and the management will be done using rancher?

thank you

**Comment by tuxtof** [comment]
second solution
you will see the VMs only in prism central and the management will be done using rancher

**Comment by pdaccache** [comment]
well noted, thank you
