### ISSUE TITLE
Not able to add cloud credentials for rke2 provisining

### ISSUE THREAD

**Issue by nn-es** [nutanix/docker-machine#57]
### Nutanix Cluster Information
Version pc.2022.4.0.1
NCC Version: 4.6.0
LCM Version: 2.6.0.1 

### Rancher Version
Rancher stable 2.7.1

### Rancher Node Driver Version
v3.3.0

### Expected Behavior
You should be able to add cloud credentials for nutanix driver via "Cluster management" > "Cloud Credentials" in the rancher menu.
Or while creating a new rke2 cluster.

### Actual Behavior
We cannot add the cloud credentials for the nutanix driver from either the cloud credentials or the add menu when creating an rke2 cluster.

Nutanix option is missing in the cloud credentials menu

<details>

<summary>screenshot</summary>

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/99181464/232058546-c314528c-9a6e-4173-b909-4c6604336d3f.png">

</details>

Its also not possible to add the credentials while creating the rke2 cluster, as the needed keys do not show up and the key fields are disabled

<details>

<summary>screenshot</summary>

<img width="295" alt="image" src="https://user-images.githubusercontent.com/99181464/232059200-8bf525b1-2800-4488-8171-ca91e1b80e11.png">

(Key field is disabled)
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/99181464/232059439-8f0fa16f-bff8-4bd0-b51a-48fbe0fbba16.png">

</details>

Please note: The deployment process, credential creation and connection to Nutanix prism is working for the rke1 cluster creation process via the node templates (which are not usable for rke2 clusters)

Can anybody help?

**Comment by tuxtof** [comment]
Can you try to update Rancher to the last version 2.7.3
i remember there is a lot of fix in 2.7.2 with RKE2

**Comment by nn-es** [comment]
Hello @tuxtof

Thanks for the update.
It seems to work out of the box with rancher 2.7.3

**Comment by tuxtof** [comment]
perfect thanks for the info
